#!/bin/sh /etc/rc.common

START=97
USE_PROCD=1

start_service() {

    # Load Configuration
    config_load docker
    config_get data_dir main data_dir

    procd_open_instance docker
    procd_set_param command /usr/bin/dockerd --data-root $data_dir

    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

    procd_set_param file /etc/config/docker
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user root


    procd_close_instance
}
