#!/bin/sh /etc/rc.common

START=97
USE_PROCD=1

start_service() {

    # Load Configuration
    config_load k3s
    config_get data_dir main data_dir
    config_get pvc_dir main pvc_dir

    procd_open_instance k3s
    procd_set_param command /usr/bin/k3s server --flannel-backend host-gw --data-dir $data_dir --default-local-storage-path $pvc_dir

    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

    procd_set_param file /etc/config/k3s
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user root


    procd_close_instance
}
