# Get latest Turris HBS tag:
# git describe --tags $(git rev-list --tags --max-count=1)
FROM debian:buster

ARG TAG=stable
ARG DEVICE=omnia
ENV TAG=$TAG
ENV DEVICE=$DEVICE
RUN echo "Building for ${DEVICE}@${TAG}"

RUN apt update && \
	apt -y install --no-install-recommends \
    # Turris OS minimum dependencies
    ca-certificates git build-essential zlib1g-dev gawk libssl-dev subversion unzip libncurses-dev wget python file rsync gcc-multilib \
    # Package & Workflow dependencies
    gettext curl xz-utils flex g++-multilib ccache python-dev python3-dev \
    # Cleanup
    && apt-get clean && rm -rf /var/lib/apt/lists/* 

# Setup build user and directories
RUN groupadd -g 2000 turris-build && useradd -u 2000 -m -g turris-build turris-build &&\
    mkdir -p /turris-build && chown turris-build:turris-build /turris-build &&\
    mkdir -p /workspace && mkdir -p /workspace/pkgs && mkdir -p /workspace/artifacts && chown -R turris-build:turris-build /workspace
USER turris-build
WORKDIR /turris-build

# Clone turris-build, checkout tag, compile toolchain
RUN git clone https://gitlab.labs.nic.cz/turris/turris-build.git /turris-build &&\
    if [ "${TAG}" = "stable" ]; then TAG=$(git describe --tags $(git rev-list --tags --max-count=1)); elif [ "${TAG}" = "latest" ]; then TAG="hbk"; fi &&\
    git checkout ${TAG}
RUN ./compile_pkgs -t ${DEVICE} prepare_tools

# VOLUME /workspace